<?php
/**
 * Qatar states
 *
 */
global $states;

$states['QA'] = array(
	'JH'   	=> __( "Al Khor", 'zoner'),
    'DH'   	=> __( "Doha", 'zoner'), 
    'HA'   	=> __( "Abu Hamour", 'zoner'), 
    'KH'  	=> __( "Ain Khaled", 'zoner'), 
    'MU'  	=> __( "Al  Muntazah", 'zoner'), 
    'BI'  	=> __( "Al Bidda", 'zoner'), 
    'DA'  	=> __( "Al Dafna", 'zoner'), 
    'DO'  	=> __( "Al Doha Al Jadeeda", 'zoner'), 
    'DU'  	=> __( "Al Duhail", 'zoner'), 
    'GH'  	=> __( "Al Gharrafa", 'zoner'), 
    'HI'  	=> __( "Al Hilal", 'zoner'),
    'JA'  	=> __( "Al Jasra", 'zoner'), 
    'JE'  	=> __( "Al Jebailat", 'zoner'), 
    'KU'  	=> __( "Al Khulaifat", 'zoner'), 
    'KW'  	=> __( "Al Khuwair", 'zoner'), 
    'AL'  	=> __( "Al Luqta / Old Al Rayyan", 'zoner'), 
    'MM'  	=> __( "Al Maamoura", 'zoner'), 
    'MN'  	=> __( "Al Mansoura / Fereej Bin Dirham", 'zoner'), 
    'MR'  	=> __( "Al Markhiya", 'zoner'), 
    'ME'  	=> __( "Al Mesaimeer", 'zoner'), 
    'MS'  	=> __( "Al Messila", 'zoner'), 
    'NA'  	=> __( "Al Najada", 'zoner'), 
    'QA'  	=> __( "Al Qassar", 'zoner'), 
    'QU'  	=> __( "Al Qutaifiya", 'zoner'), 
    'RU'  	=> __( "Al Rumaila", 'zoner'), 
    'SA'  	=> __( "Al Sadd", 'zoner'), 
    'TR'  	=> __( "Al Tarfa / Jelaiah", 'zoner'), 
    'TH'  	=> __( "Al Thumama", 'zoner'), 
    'WA'  	=> __( "Al Waab", 'zoner'),
    'AZ'  	=> __( "Al Aziziya", 'zoner'),
    'NGH'   => __( "New Al Ghanim", 'zoner'), 
    'ASZ'  	=> __( "Aspire Zone", 'zoner'), 
    'BC'  	=> __( "Barwa City", 'zoner'), 
    'BV'  	=> __( "Barwa Village", 'zoner'), 
    'DIA'  	=> __( "Doha International Airport", 'zoner'), 
    'DP'  	=> __( "Doha Port", 'zoner'), 
    'EC'  	=> __( "Education City", 'zoner'), 
    'FAA'  	=> __( "Fareej Al Ali", 'zoner'), 
    'FAZ'  	=> __( "Fereej Abdel Aziz", 'zoner'), 
    'FAE'  	=> __( "Fereej Al Ameer / Muraikh", 'zoner'), 
    'FBM'  	=> __( "Fereej Bin Mahmoud", 'zoner'), 
    'FBO'  	=> __( "Fereej Bin Omran", 'zoner'), 
    'FK'  	=> __( "Fereej Kulaib", 'zoner'), 
    'IA'  	=> __( "Industrial Area", 'zoner'), 
    'KCV'  	=> __( "Katara Cultural Village", 'zoner'), 
    'MKN'  	=> __( "Madinat Khalifa North / Dahl Al Hamam", 'zoner'), 
    'MKS'  	=> __( "Madinat Khalifa South", 'zoner'), 
    'MUS'  	=> __( "Mushaireb", 'zoner'), 
    'NAJ'  	=> __( "Najma", 'zoner'), 
    'NAR'  	=> __( "New Al Rayyan / Al Wajba", 'zoner'), 
    'NS' 	=> __( "New Salata / Al Asiri", 'zoner'), 
    'NU'  	=> __( "Nuaija", 'zoner'), 
    'OA'  	=> __( "Old Airport", 'zoner'), 
    'OG'  	=> __( "Old Al Ghanim", 'zoner'), 
    'OH'  	=> __( "Old Al Hitmi", 'zoner'), 
    'OS'  	=> __( "Old Salata", 'zoner'), 
    'ON'  	=> __( "Onaiza", 'zoner'), 
    'OT'  	=> __( "Other", 'zoner'), 
    'QNC'  	=> __( "Qatar National Convention Center", 'zoner'), 
    'RK'  	=> __( "Rawdat Al Khail", 'zoner'), 
    'SW'  	=> __( "Souq Waqif", 'zoner'), 
    'PQ'  	=> __( "The Pearl Qatar", 'zoner'), 
    'UG'  	=> __( "Umm Ghwailina", 'zoner'), 
    'UL'  	=> __( "Umm Lekhba", 'zoner'), 
    'WS'  => __( "Wadi Al Sail", 'zoner'), 
    'WB'  => __( "West Bay", 'zoner'), 
    'WK'  => __( "Wakrah", 'zoner'),
);